module.exports = {
    TEMPERATURE_THRESHOLD: 32,
    SOUND_THRESHOLD: 85,
    GAS_THRESHOLD: 300,
    TEMPERATURE_RANGE: { MIN: -30, MAX: 50 },
    SOUND_RANGE: { MIN: 0, MAX: 150 },
    GAS_RANGE: { MIN: 0, MAX: 5000 },
    _HELMET_WARNING : 1,
    _TEMPERATURE_WARNING : 2,
    _SOUND_WARNING : 3,
    _GAS_WARNING : 4,
};